sudo: required
dist: xenial

branches:
  only:
  - master
  - "/^v[0-9]/"
install:
  - sudo pip install -U pyasn1 pyopenssl
  - sudo pip install openshift --ignore-installed PyYAML
  - if [ -n "$PR_NUMBER" ]; then sudo pip install git+https://github.com/ansible/ansible.git@refs/pull/$PR_NUMBER/head; else sudo pip install git+https://github.com/ansible/ansible.git; fi
  - sudo pip install -r requirements-dev.txt
jobs:
  include:
    - stage: Tests
      name: "Default (Playbook syntax test)"

cache:
  - pip
  - directories:
    - cache
before_script:
script:
- ansible-playbook --version
- ansible-playbook -vvv --syntax-check tests/playbooks/all.yml

notifications:
  email:
    recipients:
      - omachace@redhat.com
      - mmazur@redhat.com
    on_success: never
    on_failure: always
