notifications:
  email:
    recipients:
      - mmazur@redhat.com
      - omachace@redhat.com
    on_success: never
    on_failure: always

dist: xenial
sudo: required
language: python
python:
  - "3.7"

branches:
  only:
    - master

cache:
  - pip
  - directories:
    - cache
    - "~/.minikube/cache"

# If you trigger a custom build with a custom config like this:
#   env: ANSIBLE_SOURCE=pr/9999
# then ansible from ansible.git's PR 9999 will be installed and used for executing the playbook
env:
  - ANSIBLE_SOURCE=pip
  - ANSIBLE_SOURCE=branch/stable-2.8
  - ANSIBLE_SOURCE=branch/devel

install:
  - travis/install-ansible.sh $ANSIBLE_SOURCE
  - travis/install-cluster.sh

# travis_terminate: ok=0, fail=1, error=2+
# if minikube fails to start/deploy, that should be an error
script:
  - ansible-playbook --version
  # Catch obvious errors before we spend the time on booting the cluster up:
  - ansible-playbook -vvv --syntax-check tests/playbooks/all.yml || travis_terminate 1;
  # Error out if the cluster doesn't start. This can't be inside install:, because then running a
  # quick --syntax-check before the cluster starts wouldn't be doable:
  - travis/run-cluster.sh || travis_terminate 2;
  - ansible-playbook -vvv tests/playbooks/all.yml

after_failure:
  - travis/print-debug-info.sh
