sudo: required
dist: xenial

branches:
  only:
  - master
  - "/^v[0-9]/"
install:
  - sudo pip install -U pyasn1 pyopenssl
  - sudo pip install openshift --ignore-installed PyYAML
  - if [ -n "$PR_NUMBER" ]; then sudo pip install git+https://github.com/ansible/ansible.git@refs/pull/$PR_NUMBER/head; else sudo pip install git+https://github.com/ansible/ansible.git; fi
  - sudo pip install -r requirements-dev.txt
jobs:
  include:
    - name: "minishift"
      env:
        - CPLATFORM=minishift
        - KUBEVIRT=v0.17.0
        - USE_OPERATOR=yes
        - ENABLE_DATAVOLUMES=yes

cache:
  - pip
  - directories:
    - cache
    - "~/.minishift/cache"
before_script:
## FIXME Workaround for https://github.com/kubernetes/kubernetes/issues/61058
### And https://github.com/LiliC/travis-minikube/blob/e0f26f7b388057f51a0e2558afd5f990e07b6c49/.travis.yml#L11
- sudo mount --make-rshared /

- bash -x ci/prepare-host $CPLATFORM
- bash -x ci/prepare-host virtctl $KUBEVIRT
- bash -x ci/start-cluster $CPLATFORM
- bash -x ci/deploy-kubevirt $CPLATFORM $KUBEVIRT

script:
- timeout 30m bash -x test.sh

notifications:
  email:
    recipients:
      - omachace@redhat.com
      - mmazur@redhat.com
    on_success: never
    on_failure: always
