---
language: python
python:
  - "2.7"
cache: pip
env:
  - KUBECONFIG=tests/k8s/config
install:
  - pip install -r requirements-dev.txt
script:
  - pytest
  - flake8 --ignore=E402 lib/ansible/modules
  - flake8 --ignore=E402 lib/ansible/module_utils
branches:
  # Build only tags matching vX.Y.Z-something, PRs should still be tested as it's configured directly on Travis-CI
  # https://docs.travis-ci.com/user/customizing-the-build/#Safelisting-or-blocklisting-branches
  # https://docs.travis-ci.com/user/customizing-the-build/#Using-regular-expressions
  only:
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
