---

- name: Log onto OpenShift, do something, then log out
  hosts: localhost
  connection: local
  module_defaults:
    group/k8s:
      host: https://192.168.42.55:8443
      verify_ssl: no
#      ssl_ca_cert: ca.pem
  vars:
    k8s_developer_password: zupa.8
  tasks:
  - block:
    # It's good practice to store login credentials in a secure vault and not
    # directly in playbooks.
    #- include_vars: k8s_passwords.yml

    - name: Log in (obtain auth token)
      k8s_auth:
        username: developer
        password: "{{ k8s_developer_password }}"
      register: k8s_auth_results

    # Previous task generated I(k8s_auth) fact, which you can then use
    # in k8s modules like this:
    - name: Get a list of all pods from any namespace
      k8s_facts:
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
        kind: Pod
      register: pod_list

    always:
    - name: If login succeeded, try to log out (revoke auth token)
      when: k8s_auth_results.k8s_auth.api_key is defined
      k8s_auth:
        state: absent
        api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"

