---
- name: Gather facts for test-vmips-small VirtualMachineInstancePreset
  hosts: localhost
  connection: local
  tasks:
    - k8s_facts:
        name: test-vmips-small
        namespace: default
        kind: VirtualMachineInstancePreset
        api_version: kubevirt.io/v1alpha3
      register: k8s_vmips
    - debug:
        var: k8s_vmips
