---
- name: Create a PVC from local VM image
  hosts: localhost
  connection: local
  tasks:
    - name: Create a PVC annotated for upload
      kubevirt_pvc:
       namespace: default
       name: pvc-vm1
       access_modes:
       - ReadWriteOnce
       size: 20Mi
       cdi_source:
         upload: yes
       wait: yes

    # You need to be able to connect to the cdi upload proxy specified in `upload_host` for this to work.
    # More info can be found in README.md
    - name: Upload local image to pvc
      kubevirt_cdi_upload:
        pvc_namespace: default
        pvc_name: pvc-vm1
        upload_host: https://localhost:9443
        upload_host_verify_ssl: false
        path: /tmp/cirros-0.4.0-x86_64-disk.img

