---
- name: Playbook 2
  hosts: localhost
  connection: local
  tasks:
    - name: Create first vm, for real this time
      kubevirt_vm:
        namespace: default
        name: vm1
        cpu_cores: 1
        memory: 64Mi
        disks:
          - name: containerdisk
            volume:
              containerDisk:
                image: kubevirt/cirros-container-disk-demo:latest
            disk:
              bus: virtio
