- name: Deploy application
  hosts: localhost

  vars:
    kubevirt_app_vms:
      - name: myapp
        namespace: default
        memory: 128Mi
        image:
          url: https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img
          storage: 1Gi
        labels:
          app: myappdb
        cloud_init_nocloud:
          userData: |-
            #cloud-config
            password: mypassword
            chpasswd: { expire: False }
        affinity:
          soft:
            - weight: 1
              topology_key: "kubernetes.io/hostname"
              term:
                match_expressions:
                  - key: security
                    operator: In
                    values:
                      - S1

    kubevirt_app_services:
      - name: myapp-db-service
        namespace: default
        selector:
          app: myappdb
        ports:
          - protocol: TCP
            port: 22
            targetPort: 9376

      - name: myapp-nginx-service
        namespace: default
        selector:
          app: myapphttp
        ports:
          - protocol: TCP
            port: 80
            targetPort: 9377

    kubevirt_app_deployments:
      - name: myapp
        replicas: 2
        namespace: default
        containers:
          - image: nginx
        labels:
          app: myapphttp

  roles:
    - kubevirt.app_deployment
